version: "3"

services:
  node:
    image: node:16
    volumes:
      - ./:/app
    working_dir: /app/application
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    ports:
      - 3000:3000
    command: npm run start